# Generated by Django 5.1.4 on 2024-12-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='item',
            name='delivery_days',
            field=models.IntegerField(default=1),
        ),
    ]
