# Generated by Django 5.1.4 on 2024-12-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_rename_is_active_item_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=8191),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id_str',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_days',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ItemInOrder',
        ),
    ]
