# Generated by Django 5.1.4 on 2024-12-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_alter_order_items_order_order_id_order_order_id_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
