# Generated by Django 5.1.4 on 2024-12-14 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_order_payment_method_alter_order_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 15, 44, 25, 66256, tzinfo=datetime.timezone.utc)),
        ),
    ]
