# Generated by Django 5.1.4 on 2024-12-16 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_remove_order_payment_code_alter_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 21, 57, 7, 825856, tzinfo=datetime.timezone.utc)),
        ),
    ]
