# Generated by Django 5.1.4 on 2024-12-16 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_order_paid_alter_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 22, 17, 5, 138902, tzinfo=datetime.timezone.utc)),
        ),
    ]
