# Generated by Django 5.1.4 on 2024-12-17 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_order_comments_alter_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2024, 12, 17)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 22, 11, 46, 529369, tzinfo=datetime.timezone.utc)),
        ),
    ]
