# Generated by Django 5.1.4 on 2024-12-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_item_deleted_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_path',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
