# Generated by Django 5.1.4 on 2024-12-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0011_item_photo_path_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='photo_path',
            new_name='photo_url',
        ),
    ]
